### PR TITLE
Write out raw bytes, not human-readable u8 arrays.

### PR DESCRIPTION
**Pull request by BenModulusLabs**
This is to align with what seems to be the format of a self-custody package.

### CODE REVIEW

**Comment by BenModulusLabs** [comment]
There is something strange going on with cargo fmt CI - it is passing locally for me. Line length?

**Review by NayrOacModulus — APPROVED** [review]
LGTM!

**Review by NayrOacModulus — APPROVED** [review]
LGTM again!

**Review by vishady721 — APPROVED** [review]
slayyyy

**Pull request merged**
